nameOverride: kafka
fullnameOverride: kafka
replicas:
  kafka: 3
  controller: 3
storage:
  size:
    kafka: 500Gi
    controller: 50Gi
  deleteClaim:
    kafka: "true"
    controller: "true"
template:
  pod:
    tmpDirSizeLimit:
      kafka: 500Mi
      controller: 500Mi
      entityOperator: 500Mi
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              strimzi.io/pool-name: kafka
          topologyKey: "kubernetes.io/hostname"
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              strimzi.io/pool-name: controller
          topologyKey: "kubernetes.io/hostname"
image:
  tag: "0.47.0-kafka-3.9.1_v0.28.0"
imagePullSecrets:
  - name: "instana-registry"
version: 3.9.1
kraft: "enabled"
nodePools: "enabled"
resources:
  kafka:
    requests:
      cpu: "4000m"
      memory: "20Gi"
    limits:
      memory: "20Gi"
  controller:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      memory: "2Gi"
config:
  kafka:
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    transaction.state.log.min.isr: 2
    default.replication.factor: 3
    min.insync.replicas: 2
    max.message.bytes: 52428800
    message.max.bytes: 52428800
    replica.fetch.max.bytes: 52428800
