nameOverride: kafka
fullnameOverride: kafka
replicas:
  kafka: 3
  zookeeper: 3
storage:
  size:
    kafka: 50Gi
    zookeeper: 5Gi
  deleteClaim:
    kafka: "false"
    zookeeper: "false"
template:
  pod:
    tmpDirSizeLimit:
      kafka: 500Mi
      zookeeper: 500Mi
      entityOperator: 500Mi
image:
  tag: "0.45.0-kafka-3.8.1_v0.15.0"
imagePullSecrets:
  - name: "instana-registry"
version: 3.7.1
