nameOverride: kafka
fullnameOverride: kafka
replicas:
  kafka: 3
  controller: 3
storage:
  size:
    kafka: 50Gi
    controller: 5Gi
  deleteClaim:
    kafka: "false"
    controller: "false"
template:
  pod:
    tmpDirSizeLimit:
      kafka: 500Mi
      controller: 500Mi
      entityOperator: 500Mi
image:
  tag: "0.47.0-kafka-3.9.1_v0.24.0"
imagePullSecrets:
  - name: "instana-registry"
version: 3.9.1
kraft: "enabled"
nodePools: "enabled"
