nameOverride: postgres
fullnameOverride: postgres
instances: 3
postgresql:
  parameters:
    shared_buffers: 256MB
    wal_keep_size: "2GB"
    wal_receiver_timeout: "30s"
    wal_sender_timeout: "30s"
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    memory: 1Gi
affinity:
  podAntiAffinityType: preferred
storage:
  size: 50Gi
image:
  tag: "15_v0.34.0"
imagePullSecrets:
  - name: "instana-registry"
