baseDomain: ""
# agentAcceptorConfig:
#   host: ""
#   port: 443
acceptors:
  agent:
    host: ""
    port: 443
  otlp:
    http: {}
    grpc: {}
  synthetics: {}
  serverless: {}
  eum: {}
gatewayConfig:
  # -- Enable gateway-controller with gateway-v2
  enabled: true
  gateway:
    # -- Image config for the gateway image
    imageConfig: {}
    # -- Number of gateway replicas
    replicas: 1
    # -- Log level for gateway
    logLevel: error
    # -- Listener IP for gateway admin endpoint
    adminListener: 127.0.0.1
    # -- Circuit breaker configuration for Gateway acceptor ingress traffic.
    circuitBreakers:
      maxConnections: 50000
      maxPendingRequests: 50000
      maxRequests: 50000
      maxRetries: 4
    # -- Deployment configuration for the gateway
    config: {}
  controller:
    # -- Image config for the gateway image
    imageConfig: {}
    # -- Number of gateway replicas
    replicas: 1
    # -- List of TLS cipher suites to use
    tlsCipherSuites: []
    # -- Deployment configuration for the gateway-controller
    config: {}
tenantUnits: []
deploymentStrategyType: RollingUpdate
dhParams: ""
repositoryPassword: ""
salesKey: ""
customCACert: ""
emailConfig:
  smtpConfig:
    check_server_identity: false
    from: ""
    host: ""
    port: 25
    startTLS: false
    useSSL: true
    user: ""
    password: ""
imagePullSecrets:
  - name: instana-registry
imagePullPolicy: IfNotPresent
storageConfigs:
  rawSpans: {}
  eumSourceMaps: {}
  synthetics: {}
  syntheticsKeystore: {}
resourceProfile: small
properties: []
featureFlags:
  - name: feature.beeinstana.infra.metrics.enabled
    enabled: true
serviceAccountAnnotations: {}
serviceProviderConfig: ""
componentConfigs: []
datastores:
  cassandra:
    hosts:
      - "instana-cassandra-service.instana-cassandra.svc"
    datacenter: cassandra
    replicationFactor: 1
    adminUser: instanaadmin
    adminPassword: ""
    user: instana
    password: ""
  clickhouse:
    hosts:
      - "chi-clickhouse-local-0-0.instana-clickhouse.svc"
      - "chi-clickhouse-local-0-1.instana-clickhouse.svc"
    clusterName: local
    adminUser: instanaadmin
    adminPassword: ""
    user: instana
    password: ""
  kafka:
    hosts:
      - "kafka-kafka-bootstrap.instana-kafka.svc"
    saslMechanism: SCRAM-SHA-512
    replicationFactor: 1
    adminUser: instanaadmin
    adminPassword: ""
    consumerUser: instana
    consumerPassword: ""
    producerUser: instana
    producerPassword: ""
  elasticsearch:
    hosts:
      - "elasticsearch-es-http.instana-elastic.svc"
    clusterName: instana
    adminUser: instanaadmin
    adminPassword: ""
    user: instana
    password: ""
  beeInstana:
    hosts:
      - "aggregators.instana-beeinstana.svc"
    user: instana
    password: ""
  postgres:
    hosts:
      - "postgres-rw.instana-postgres.svc"
    adminUser: instanaadmin
    adminPassword: ""
    user: instana
    password: ""
proxyConfig:
  host: ""
  port: 80
  nonProxyHosts: []
  user: ""
  password: ""
operationMode: normal
env: []
geoDbUrl: ""
geoDbUser: ""
geoDbPassword: ""
priorityClassName: ""
tokenSecret: ""
cert:
  crt: ""
  key: ""
services: []
