storageConfigs:
  rawSpans:
    gcloudConfig:
      bucket: ""
      bucketLongTerm: ""
      prefix: ""
      prefixLongTerm: ""
      storageClass: ""
      storageClassLongTerm: ""
  eumSourceMaps:
    gcloudConfig:
      bucket: ""
      bucketLongTerm: ""
      prefix: ""
      prefixLongTerm: ""
      storageClass: ""
      storageClassLongTerm: ""
serviceAccountAnnotations:
  iam.gke.io/gcp-service-account: ""
services: 
- nameSuffix: lb-acceptor
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: http-service
  selectorLabels:
    app.kubernetes.io/component: acceptor
    app.kubernetes.io/name: instana
    instana.io/group: service
  type: LoadBalancer
  loadBalancerIP: "" 
- nameSuffix: lb-gateway
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selectorLabels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/name: instana
    instana.io/group: service
  type: LoadBalancer  
  loadBalancerIP: ""
