domains:
  base: ""
  otlpHttp: ""
  otlpGrpc: ""
agentAcceptor:
  host: ""
  port: 443
tenantUnits:
  - unitName: unit0
    tenantName: tenant0
deploymentStrategyType: RollingUpdate
dhParams: ""
repositoryPassword: ""
salesKey: ""
customCACert: ""
emailConfig:
  smtpConfig:
    check_server_identity: false
    from: ""
    host: ""
    port: 25
    startTLS: false
    useSSL: true
    user: ""
    password: ""
imageConfig:
  registry: artifact-public.instana.io
imagePullSecrets:
  - name: instana-registry
imagePullPolicy: IfNotPresent
storageConfigs:
  rawSpans: {}
  eumSourceMaps: {}
  synthetics: {}
  syntheticsKeystore: {}
resourceProfile: small
properties: []
featureFlags:
  - name: feature.beeinstana.infra.metrics.enabled
    enabled: true
serviceAccountAnnotations: {}
serviceProviderConfig: ""
componentConfigs: []
datastores:
  cassandra:
    hosts: ["instana-cassandra-service.instana-cassandra.svc"]
    datacenter: cassandra
    replicationFactor: 1
    adminUser: instanaadmin
    adminPassword: ""
    user: instana
    password: ""
  clickhouse:
    hosts: ["chi-clickhouse-local-0-0.instana-clickhouse.svc", "chi-clickhouse-local-0-1.instana-clickhouse.svc"]
    clusterName: local
    adminUser: instanaadmin
    adminPassword: ""
    user: instanaadmin
    password: ""
  kafka:
    hosts: ["kafka-kafka-bootstrap.instana-kafka.svc"]
    saslMechanism: SCRAM-SHA-512
    replicationFactor: 1
    adminUser: instanaadmin
    adminPassword: ""
    consumerUser: instana
    consumerPassword: ""
    producerUser: instana
    producerPassword: ""
  elasticsearch:
    hosts: ["elasticsearch-es-http.instana-elastic.svc"]
    clusterName: instana
    adminUser: instanaadmin
    adminPassword: ""
    user: instana
    password: ""
  beeInstana:
    hosts: ["aggregators.instana-beeinstana.svc"]
    user: instana
    password: ""
  postgres:
    hosts: ["postgres-rw.instana-postgres.svc"]
    adminUser: instanaadmin
    adminPassword: ""
    user: instana
    password: ""
proxyConfig:
  host: ""
  port: 80
  nonProxyHosts: []
  user: ""
  password: ""
operationMode: normal
env: []
geoDbUrl: ""
geoDbUser: ""
geoDbPassword: ""
priorityClassName: ""
tokenSecret: ""
cert:
  crt: ""
  key: ""
services:
- nameSuffix: lb-acceptor
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: http-service
  selectorLabels:
    app.kubernetes.io/component: acceptor
    app.kubernetes.io/name: instana
    instana.io/group: service
  type: LoadBalancer
  externalTrafficPolicy: Local
- nameSuffix: lb-gateway
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selectorLabels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/name: instana
    instana.io/group: service
  type: LoadBalancer
  externalTrafficPolicy: Local
