apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-volume
spec:
  capacity:
    storage: {{AZURE_STORAGE_CAPACITY}}
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-storage-account
    shareName: {{AZURE_STORAGE_FILESHARE_NAME}}
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
