nameOverride: elasticsearch
fullnameOverride: elasticsearch
nodeSets:
  - name: default
    count: 3
    containerName: "elasticsearch"
    config:
      node.roles:
        - master
        - ingest
        - data
      node.store.allow_mmap: false
    resources:
      requests:
        cpu: "2000m"
        memory: "8Gi"
      limits:
        memory: "8Gi"
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    storageClassName: ""
    volume:
      resources:
        requests:
          storage: 500Gi
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: instana
                topologyKey: "kubernetes.io/hostname"
image:
  tag: "8.18.6_v0.16.10"
imagePullSecrets:
  - name: "instana-registry"
version: 8.18.6
