nodeSets:
  - name: default
    count: 3
    containerName: "elasticsearch"
    config:
      node.roles:
        - master
        - ingest
        - data
      node.store.allow_mmap: false
    resources:
      requests:
        cpu: "2000m"
        memory: "8Gi"
      limits:
        memory: "8Gi"
    securityContext: {}
    storageClassName: ""
    volume:
      resources:
        requests:
          storage: 500Gi
