nameOverride: elasticsearch
fullnameOverride: elasticsearch
nodeSets:
  - name: default
    count: 3
    containerName: "elasticsearch"
    priorityClassName: "system-cluster-critical"
    config:
      node.roles:
        - master
        - ingest
        - data
      node.store.allow_mmap: false
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    storageClassName: ""
    volume:
      resources:
        requests:
          storage: 20Gi
