nameOverride: beeinstana
fullnameOverride: beeinstana
imagePullSecretName: "instana-registry"
aggregator:
  cpu: 4
  memory: 16Gi
  mirrors: 2
  shards: 1
  volumes:
    live:
      size: 2000Gi
      storageClass: ""
config:
  cpu: 200m
  memory: 200Mi
  replicas: 1
ingestor:
  cpu: 8
  memory: 4Gi
  replicas: 1
  workerPoolSize: 20
  flushInterval: 10000
  maxQueueSize: 5000
