nameOverride: beeinstana
fullnameOverride: beeinstana
version: "1.3.24"
imagePullSecretName: "instana-registry"
aggregator:
  image:
    tag: v1.85.76-release
  cpu: 4
  memory: 16Gi
  mirrors: 2
  shards: 1
  volumes:
    live:
      size: 2000Gi
      storageClass: ""
config:
  image:
    tag: v2.44.0
  cpu: 200m
  memory: 200Mi
  replicas: 1
ingestor:
  image:
    tag: v1.85.76-release
  cpu: 8
  memory: 4Gi
  replicas: 1
  workerPoolSize: 20
  flushInterval: 10000
  maxQueueSize: 5000
