initialAdminUser: admin@instana.local
initialAdminPassword: "mypass"
resourceProfile: medium
properties: []
componentConfigs: []
priorityClassName: ""
env: []
coreName: "instana-core"
coreNamespace: "instana-core"
imagePullSecrets:
  - name: "instana-registry"
