tenantName: "tenant0"
unitName: "unit0"
initialAdminUser: admin@instana.local
initialAdminPassword: "mypass"
properties: []
componentConfigs: []
priorityClassName: ""
env: []
coreName: "instana-core"
coreNamespace: "instana-core"
