image:
  tag: 0.45.0_v0.17.0
  name: "strimzi"
  imagePullSecrets:
    - name: "instana-registry"
topicOperator:
  image:
    tag: 0.45.0_v0.17.0
    name: "strimzi"
userOperator:
  image:
    tag: 0.45.0_v0.17.0
    name: "strimzi"
