image:
  tag: 0.45.0_v0.15.0
  name: "strimzi"
  imagePullSecrets:
    - name: "instana-registry"
topicOperator:
  image:
    tag: 0.45.0_v0.15.0
    name: "strimzi"
userOperator:
  image:
    tag: 0.45.0_v0.15.0
    name: "strimzi"
tlsSidecarEntityOperator:
  image:
    tag: 0.45.0-kafka-3.8.1_v0.15.0
    name: "kafka"
