image:
  tag: 0.42.0_v0.12.0
  name: "strimzi"
  imagePullSecrets:
    - name: "instana-registry"
topicOperator:
  image:
    tag: 0.42.0_v0.12.0
    name: "strimzi"
userOperator:
  image:
    tag: 0.42.0_v0.12.0
    name: "strimzi"
tlsSidecarEntityOperator:
  image:
    tag: 0.42.0-kafka-3.7.1_v0.11.0
    name: "kafka"
