image:
  tag: 0.47.0_v0.20.0
  name: "strimzi"
  imagePullSecrets:
    - name: "instana-registry"
topicOperator:
  image:
    tag: 0.47.0_v0.20.0
    name: "strimzi"
userOperator:
  image:
    tag: 0.47.0_v0.20.0
    name: "strimzi"
