image:
  name: "strimzi"
  registry: "artifact-public.instana.io"
  repository: "self-hosted-images/3rd-party/operator"
topicOperator:
  image:
    name: "strimzi"
    registry: "artifact-public.instana.io"
    repository: "self-hosted-images/3rd-party/operator"
userOperator:
  image:
    name: "strimzi"
    registry: "artifact-public.instana.io"
    repository: "self-hosted-images/3rd-party/operator"
