nameOverride: cassandra
fullnameOverride: cassandra
size: 3
resources:
  requests:
    cpu: 1000m
    memory: 4Gi
jvmServerOptions:
  initialHeapSize: 4G
  maxHeapSize: 8G
storageClassName: ""
storage: 100Gi
memtableFlushWriters: 8
image:
  tag: "4.1.4_v0.19.0"
imagePullSecrets:
  - name: "instana-registry"
version: 4.1.4
