nameOverride: cassandra
fullnameOverride: cassandra
priorityClassName: "system-cluster-critical"
size: 3
resources:
  requests:
    cpu: 1000m
    memory: 4Gi
jvmServerOptions:
  initialHeapSize: 4G
  maxHeapSize: 8G
storageClassName: ""
storage: 100Gi
memtableFlushWriters: 8
