nameOverride: cassandra
fullnameOverride: cassandra
size: 3
resources:
  requests:
    cpu: 4000m
    memory: 12Gi
  limits:
    memory: 12Gi
jvmServerOptions:
  initialHeapSize: 4G
  maxHeapSize: 8G
storageClassName: ""
storage: 500Gi
memtableFlushWriters: 8
image:
  tag: "4.1.8_v0.35.0"
imagePullSecrets:
  - name: "instana-registry"
version: 4.1.8
