image: "artifact-public.instana.io/self-hosted-images/3rd-party/datastore/cassandra:4.1.4_v0.19.0"
version: "4.1.4"
priorityClassName: "system-cluster-critical"
size: 3
resources:
  requests:
    cpu: 1000m
    memory: 4Gi
jvmServerOptions:
  initialHeapSize: 4G
  maxHeapSize: 8G
storageClassName: ""
storage: 100Gi
memtableFlushWriters: 8
